2018-01-03 12:45:00 Error: [Cake\Database\Exception] Impossible to generate condition with empty list of values for field (request_id) in /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Database/Expression/Comparison.php on line 228
Request URL: /
Client IP: 127.0.0.1
Stack Trace:
#0 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Database/Expression/Comparison.php(160): Cake\Database\Expression\Comparison->_stringExpression(Object(Cake\Database\ValueBinder))
#1 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Database/Expression/QueryExpression.php(546): Cake\Database\Expression\Comparison->sql(Object(Cake\Database\ValueBinder))
#2 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Database/QueryCompiler.php(134): Cake\Database\Expression\QueryExpression->sql(Object(Cake\Database\ValueBinder))
#3 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Database/Query.php(312): Cake\Database\QueryCompiler->Cake\Database\{closure}(Object(Cake\Database\Expression\QueryExpression), 'where')
#4 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Database/QueryCompiler.php(99): Cake\Database\Query->traverse(Object(Closure), Array)
#5 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Database/Driver.php(361): Cake\Database\QueryCompiler->compile(Object(Cake\ORM\Query), Object(Cake\Database\ValueBinder))
#6 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Database/Connection.php(301): Cake\Database\Driver->compileQuery(Object(Cake\ORM\Query), Object(Cake\Database\ValueBinder))
#7 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Database/Query.php(283): Cake\Database\Connection->compileQuery(Object(Cake\ORM\Query), Object(Cake\Database\ValueBinder))
#8 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/ORM/Query.php(1020): Cake\Database\Query->sql(Object(Cake\Database\ValueBinder))
#9 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Database/Driver/Sqlite.php(105): Cake\ORM\Query->sql()
#10 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Database/Connection.php(260): Cake\Database\Driver\Sqlite->prepare(Object(Cake\ORM\Query))
#11 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Database/Connection.php(313): Cake\Database\Connection->prepare(Object(Cake\ORM\Query))
#12 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Database/Query.php(214): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#13 /opt/lampp/htdocs/cake-auth/vendor/cakephp/debug_kit/src/Model/Table/RequestsTable.php(102): Cake\Database\Query->execute()
#14 /opt/lampp/htdocs/cake-auth/vendor/cakephp/debug_kit/src/ToolbarService.php(183): DebugKit\Model\Table\RequestsTable->gc()
#15 /opt/lampp/htdocs/cake-auth/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(53): DebugKit\ToolbarService->saveData(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#19 /opt/lampp/htdocs/cake-auth/webroot/index.php(40): Cake\Http\Server->run()
#20 {main}


2018-01-03 14:22:02 Error: [Cake\Routing\Exception\MissingControllerException] Controller class CakeAuth could not be found.
Exception Attributes: array (
  'class' => 'CakeAuth',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /cake-auth/users
Stack Trace:
#0 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ControllerFactory.php(38): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(90): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 /opt/lampp/htdocs/cake-auth/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 /opt/lampp/htdocs/cake-auth/webroot/index.php(40): Cake\Http\Server->run()
#15 {main}


2018-01-03 14:22:12 Error: [Cake\Routing\Exception\MissingControllerException] Controller class CakeAuth could not be found.
Exception Attributes: array (
  'class' => 'CakeAuth',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /cake-auth/users/add
Stack Trace:
#0 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ControllerFactory.php(38): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(90): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 /opt/lampp/htdocs/cake-auth/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 /opt/lampp/htdocs/cake-auth/webroot/index.php(40): Cake\Http\Server->run()
#15 {main}


2018-01-03 14:24:18 Error: [Cake\Controller\Exception\MissingActionException] Action UsersController::login() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
  'prefix' => '',
  'plugin' => false,
)
Request URL: /
Stack Trace:
#0 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#1 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsersController))
#2 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 /opt/lampp/htdocs/cake-auth/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 /opt/lampp/htdocs/cake-auth/webroot/index.php(40): Cake\Http\Server->run()
#15 {main}


2018-01-03 19:52:22 Error: [Error] Class 'App\Model\Entity\DefaultPasswordHasher' not found
Request URL: /users/signup
Referer URL: http://localhost:8765/users/signup
Stack Trace:
#0 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Datasource/EntityTrait.php(264): App\Model\Entity\User->_setPassword('odiesd')
#1 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/ORM/Marshaller.php(593): Cake\ORM\Entity->set(Array)
#2 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/ORM/Table.php(2512): Cake\ORM\Marshaller->merge(Object(App\Model\Entity\User), Array, Array)
#3 /opt/lampp/htdocs/cake-auth/src/Controller/UsersController.php(71): Cake\ORM\Table->patchEntity(Object(App\Model\Entity\User), Array)
#4 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Controller/Controller.php(440): App\Controller\UsersController->signup()
#5 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#6 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsersController))
#7 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 /opt/lampp/htdocs/cake-auth/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#19 /opt/lampp/htdocs/cake-auth/webroot/index.php(40): Cake\Http\Server->run()
#20 {main}


2018-01-03 21:19:50 Error: [Cake\View\Exception\MissingElementException] Element file "Element/Flash/warning.ctp" is missing.
Exception Attributes: array (
  0 => 'Element/Flash/warning.ctp',
)
Request URL: /users
Referer URL: http://localhost:8765/?redirect=%2Fusers
Stack Trace:
#0 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/View/Helper/FlashHelper.php(89): Cake\View\View->element('Flash/warning', Array)
#1 /opt/lampp/htdocs/cake-auth/src/Template/Layout/default.ctp(55): Cake\View\Helper\FlashHelper->render()
#2 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/View/View.php(1196): include('/opt/lampp/htdo...')
#3 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/View/View.php(1157): Cake\View\View->_evaluate('/opt/lampp/htdo...', Array)
#4 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/View/View.php(812): Cake\View\View->_render('/opt/lampp/htdo...')
#5 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/View/View.php(770): Cake\View\View->renderLayout('', 'default')
#6 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Controller/Controller.php(623): Cake\View\View->render(NULL, NULL)
#7 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(125): Cake\Controller\Controller->render()
#8 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsersController))
#9 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 /opt/lampp/htdocs/cake-auth/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#19 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#21 /opt/lampp/htdocs/cake-auth/webroot/index.php(40): Cake\Http\Server->run()
#22 {main}


2018-01-03 22:11:30 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "users"
Request URL: /users/view/users/view/5
Referer URL: http://localhost:8765/users/view/5
Stack Trace:
#0 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/ORM/Table.php(1445): Cake\ORM\Query->firstOrFail()
#1 /opt/lampp/htdocs/cake-auth/src/Controller/UsersController.php(38): Cake\ORM\Table->get(Array, Array)
#2 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Controller/Controller.php(440): App\Controller\UsersController->view('users', 'view', '5')
#3 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#4 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsersController))
#5 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#6 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#7 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 /opt/lampp/htdocs/cake-auth/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 /opt/lampp/htdocs/cake-auth/webroot/index.php(40): Cake\Http\Server->run()
#18 {main}


2018-01-03 22:11:43 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "users"
Request URL: /users/view/users/view/5
Referer URL: http://localhost:8765/users/view/5
Stack Trace:
#0 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/ORM/Table.php(1445): Cake\ORM\Query->firstOrFail()
#1 /opt/lampp/htdocs/cake-auth/src/Controller/UsersController.php(38): Cake\ORM\Table->get(Array, Array)
#2 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Controller/Controller.php(440): App\Controller\UsersController->view('users', 'view', '5')
#3 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#4 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsersController))
#5 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#6 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#7 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 /opt/lampp/htdocs/cake-auth/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 /opt/lampp/htdocs/cake-auth/webroot/index.php(40): Cake\Http\Server->run()
#18 {main}


2018-01-03 22:12:07 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "users"
Request URL: /users/view/users/view/5
Referer URL: http://localhost:8765/users/view/5
Stack Trace:
#0 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/ORM/Table.php(1445): Cake\ORM\Query->firstOrFail()
#1 /opt/lampp/htdocs/cake-auth/src/Controller/UsersController.php(38): Cake\ORM\Table->get(Array, Array)
#2 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Controller/Controller.php(440): App\Controller\UsersController->view('users', 'view', '5')
#3 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#4 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsersController))
#5 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#6 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#7 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 /opt/lampp/htdocs/cake-auth/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 /opt/lampp/htdocs/cake-auth/webroot/index.php(40): Cake\Http\Server->run()
#18 {main}


2018-01-03 22:12:21 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "users"
Request URL: /users/view/users/view/5
Referer URL: http://localhost:8765/users/view/5
Stack Trace:
#0 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/ORM/Table.php(1445): Cake\ORM\Query->firstOrFail()
#1 /opt/lampp/htdocs/cake-auth/src/Controller/UsersController.php(38): Cake\ORM\Table->get(Array, Array)
#2 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Controller/Controller.php(440): App\Controller\UsersController->view('users', 'view', '5')
#3 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#4 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsersController))
#5 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#6 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#7 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 /opt/lampp/htdocs/cake-auth/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 /opt/lampp/htdocs/cake-auth/webroot/index.php(40): Cake\Http\Server->run()
#18 {main}


2018-01-03 23:38:56 Warning: Warning (2): A non-numeric value encountered in [/opt/lampp/htdocs/cake-auth/src/Template/Users/index.ctp, line 35]
Request URL: /users
Referer URL: http://localhost:8765/?redirect=%2Fusers
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 153
include - APP/Template/Users/index.ctp, line 35
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1196
Cake\View\View::_render() - CORE/src/View/View.php, line 1157
Cake\View\View::render() - CORE/src/View/View.php, line 765
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 623
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 125
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 108
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 104
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 98
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 81
[main] - ROOT/webroot/index.php, line 40



2018-01-03 23:38:56 Warning: Warning (2): A non-numeric value encountered in [/opt/lampp/htdocs/cake-auth/src/Template/Users/index.ctp, line 35]
Request URL: /users
Referer URL: http://localhost:8765/?redirect=%2Fusers
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 153
include - APP/Template/Users/index.ctp, line 35
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1196
Cake\View\View::_render() - CORE/src/View/View.php, line 1157
Cake\View\View::render() - CORE/src/View/View.php, line 765
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 623
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 125
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 108
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 104
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 98
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 81
[main] - ROOT/webroot/index.php, line 40



2018-01-04 00:20:24 Error: [ParseError] syntax error, unexpected '']) ?>' (T_CONSTANT_ENCAPSED_STRING), expecting ']'
Request URL: /users
Stack Trace:
#0 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/View/View.php(1157): Cake\View\View->_evaluate('/opt/lampp/htdo...', Array)
#1 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/View/View.php(765): Cake\View\View->_render('/opt/lampp/htdo...')
#2 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Controller/Controller.php(623): Cake\View\View->render(NULL, NULL)
#3 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(125): Cake\Controller\Controller->render()
#4 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsersController))
#5 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#6 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#7 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 /opt/lampp/htdocs/cake-auth/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 /opt/lampp/htdocs/cake-auth/webroot/index.php(40): Cake\Http\Server->run()
#18 {main}


2018-01-04 00:20:26 Error: [ParseError] syntax error, unexpected '']) ?>' (T_CONSTANT_ENCAPSED_STRING), expecting ']'
Request URL: /users
Stack Trace:
#0 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/View/View.php(1157): Cake\View\View->_evaluate('/opt/lampp/htdo...', Array)
#1 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/View/View.php(765): Cake\View\View->_render('/opt/lampp/htdo...')
#2 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Controller/Controller.php(623): Cake\View\View->render(NULL, NULL)
#3 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(125): Cake\Controller\Controller->render()
#4 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsersController))
#5 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#6 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#7 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 /opt/lampp/htdocs/cake-auth/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 /opt/lampp/htdocs/cake-auth/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 /opt/lampp/htdocs/cake-auth/webroot/index.php(40): Cake\Http\Server->run()
#18 {main}


